
OBJ     =       shape2ogr.obj shpopen.obj dbfopen.obj ogrshapedriver.obj \
		ogrshapedatasource.obj ogrshapelayer.obj shptree.obj sbnsearch.obj \
		shp_vsi.obj
EXTRAFLAGS =	-I.. -I..\.. -I..\generic /DSHAPELIB_DLLEXPORT \
		-DUSE_CPL -DSAOffset=vsi_l_offset 

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)
# Cadcorp
	lib /out:shptreelib.lib shpopen.obj shptree.obj shp_vsi.obj sbnsearch.obj
# Cadcorp

clean:
	-del *.obj *.pdb



